sudo: true

language: php

php:
 - 7.2

before_script:
 - mkdir plugins
 - mkdir artifacts
 - rm -rf plugins
 - rm -rf bin
 - rm -rf artifacts
# - pecl install channel://pecl.php.net/pthreads-3.1.6
 - echo | pecl install channel://pecl.php.net/yaml-2.0.2
 - git clone https://github.com/krakjoe/pthreads.git
 - cd pthreads
 - git checkout 6c6b15138c923b69cfa46ee05fc2dd45da587287
 - phpize
 - ./configure
 - make
 - make install
 - cd ..
 - echo "extension=pthreads.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
 - composer install
 - wget -O plugins/DevTools.phar https://github.com/pmmp/PocketMine-DevTools/releases/download/v1.12.9/DevTools_v1.12.9.phar --no-check-certificate
 - wget -O PHP7.tar.gz https://jenkins.pmmp.io/job/PHP-7.2-Linux-x86_64/lastSuccessfulBuild/artifact/PHP_Linux-x86_64.tar.gz --no-check-certificate
 
script:
 - php ci.php

notifications:
 email: false
  
 before_deploy:
 - mv plugins/DevTools/Apollo*.phar plugins/DevTools/Apollo.phar
